### ISSUE TITLE
Author propagation broken

### ISSUE THREAD

**Issue by Qwlouse** [Qwlouse/Findeco#317]
It seems that carrying the old authors over to a new proposal is broken. This is illustrated by this example:
https://findeco.piraten-rlp.de/Wahlprogramm_RLP.10/Bildung.2/E-Learning.2
https://findeco.piraten-rlp.de/Wahlprogramm_RLP.10/Bildung.2/E-Learning.3

**Comment by pinae** [comment]
I just testet this. The author propagation in 0.5 is not broken.
